name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check formatting
      run: cargo fmt --all -- --check
    - name: Run lint
      run: cargo clippy --workspace --all-targets --verbose --all-features
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      env:
        X_API_KEY: ${{ secrets.API_KEY }}
      run: cargo test --verbose
